-- Auditoria de integração entre os apps (SOMENTE LEITURA; nada é gravado). Cada linha = uma ligação entre apps; viol = quantos registros a violam (0 = íntegro).
-- Rodar no Dev (SQL Editor ou execute_sql). Zero também aparece quando a tabela está vazia: conferir o volume (consulta ao final) antes de concluir que a ligação foi provada.
with net as (select receivable_id, sum(case when kind='payment' then amount_cents else -amount_cents end) n from public.payments group by 1),
rs as (select sale_id, count(*) c, sum(amount_cents) s from public.receivables group by 1),
sale_net as (select r.sale_id, coalesce(sum(n.n),0) n from public.receivables r left join net n on n.receivable_id=r.id group by 1)
select '01 venda confirmada sem parcelas' chk, count(*) viol, 'sales→receivables' ligacao from public.sales s where s.status='confirmed' and not exists (select 1 from rs where rs.sale_id=s.id)
union all select '02 parcelas não somam o total da venda', count(*), 'sales→receivables' from public.sales s join rs on rs.sale_id=s.id where s.status='confirmed' and rs.s<>s.total_cents
union all select '03 recebido líquido maior que a parcela', count(*), 'receivables→payments' from public.receivables r join net on net.receivable_id=r.id where net.n>r.amount_cents
union all select '04 parcela de outra pessoa que a da venda', count(*), 'sales→receivables' from public.receivables r join public.sales s on s.id=r.sale_id where r.person_id is distinct from s.person_id
union all select '05 venda confirmada de pacote sem client_package', count(*), 'sales→pacote' from public.sales s where s.status='confirmed' and exists (select 1 from public.sale_items i join public.products p on p.id=i.product_id where i.sale_id=s.id and p.kind='package') and not exists (select 1 from public.client_packages c where c.sale_id=s.id)
union all select '06 pacote de outra pessoa que a da venda', count(*), 'sales→pacote' from public.client_packages c join public.sales s on s.id=c.sale_id where c.person_id<>s.person_id
union all select '07 saldo do pacote negativo ou acima do total', count(*), 'pacote→session_ledger' from (select c.id, c.total_sessions, coalesce(sum(l.delta),0) sd from public.client_packages c left join public.session_ledger l on l.client_package_id=c.id group by 1,2) x where x.sd<0 or x.sd>x.total_sessions
union all select '08 agendamento usa pacote de outra pessoa', count(*), 'agenda→pacote' from public.appointments a join public.client_packages c on c.id=a.client_package_id where c.person_id<>a.person_id
union all select '09 comissão cujo pagamento não existe', count(*), 'payments→comissões' from public.commission_entries e where e.payment_id is not null and not exists (select 1 from public.payments p where p.id=e.payment_id)
union all select '10 comissão ligada a venda diferente da do pagamento', count(*), 'payments→comissões' from public.commission_entries e join public.payments p on p.id=e.payment_id join public.receivables r on r.id=p.receivable_id where r.sale_id<>e.sale_id
union all select '11 estorno sem lançamento de comissão quando o original gerou', count(*), 'estorno→comissões' from public.payments rf where rf.kind='refund' and exists (select 1 from public.commission_entries e where e.payment_id=rf.refund_of) and not exists (select 1 from public.commission_entries e where e.payment_id=rf.id)
union all select '12 acesso ativo de compra com venda cancelada ou sem recebimento líquido', count(*), 'venda→Academy' from public.entitlements en join public.sales s on s.id=en.source_ref join sale_net sn on sn.sale_id=s.id where en.source='purchase' and en.revoked_at is null and (s.status='cancelled' or sn.n<=0)
union all select '13 indicação cuja oportunidade é de outra pessoa', count(*), 'parceiro→CRM' from public.referrals rf join public.opportunities o on o.id=rf.opportunity_id where o.person_id<>rf.referred_person_id
union all select '14 repasse autorizado/pago sem conta a pagar (legado)', count(*), 'parceiros→Financeiro' from public.partner_payouts where status in ('authorized','paid') and payable_id is null
union all select '15 repasse pago com conta a pagar não paga', count(*), 'parceiros→Financeiro' from public.partner_payouts pp join public.payables p on p.id=pp.payable_id where pp.status='paid' and p.status<>'paid'
union all select '16 captação (formulário) sem pessoa', count(*), 'Pages→cadastro' from public.form_submissions where person_id is null
union all select '17 captação com oportunidade de outra pessoa', count(*), 'Pages→CRM' from public.form_submissions f join public.opportunities o on o.id=f.opportunity_id where o.person_id<>f.person_id
union all select '18 conversa com oportunidade de outra pessoa', count(*), 'CRM→Conversas' from public.crm_conversations c join public.opportunities o on o.id=c.opportunity_id where o.person_id<>c.person_id
union all select '19 oportunidade aberta duplicada (mesma pessoa e funil)', count(*), 'CRM' from (select person_id, pipeline_id from public.opportunities where status='open' group by 1,2 having count(*)>1) d
union all select '20 mais de uma venda pendente por oportunidade', count(*), 'CRM→venda' from (select opportunity_id from public.sales where status='pending' and opportunity_id is not null group by 1 having count(*)>1) d
union all select '21 venda confirmada de oportunidade que não está ganha (informativo)', count(*), 'CRM→venda' from public.sales s join public.opportunities o on o.id=s.opportunity_id where s.status='confirmed' and o.status<>'won'
order by 1;

-- Volume de cada ligação (zero = a verificação acima não prova nada para aquela ligação)
-- select 'vendas confirmadas' t, count(*) n from public.sales where status='confirmed' union all select 'pagamentos', count(*) from public.payments union all select 'estornos', count(*) from public.payments where kind='refund' union all select 'pacotes de cliente', count(*) from public.client_packages union all select 'comissões', count(*) from public.commission_entries union all select 'matrículas Academy', count(*) from public.entitlements union all select 'indicações', count(*) from public.referrals union all select 'repasses a parceiros', count(*) from public.partner_payouts union all select 'conversas', count(*) from public.crm_conversations;
